otherMessages:
  itemDropDestruction:
    confirmMessage: "&cAre you sure you want to destroy this item? If so, drop it from your inventory &e1 &cmore time to confirm. You will NOT be able to get this item back in your inventory!%nl%&eNote: destruction request will be removed from our system in &b5 &eseconds if no action was taken."
    destroyedMessage: "&aItem has been destroyed."
  invalidArguments:
    admin:
      - "&6PvP &eHelp Commands"
      - "&7"
      - "&e/pvp shop &7Opens shop menu"
      - "&e/pvp setShopNPC &7Creates a shop npc"
      - "&e/pvp setProfileNPC &7Creates a profile npc"
      - "&e/pvp setGameLocation &7Sets game location"
      - "&e/pvp reload &7Reloads config and data files"
      - "&e/pvp removeNPC <ID> &7Removes NPC with a specific ID"
      - "&e/pvp toggleProfile &7Locks/Unlocks your profile"
      - "&e/pvp profile [player] &7Checks profile of yours or others"
    player:
      - "&6PvP &eHelp Commands"
      - "&7"
      - "&e/pvp shop &7Opens shop menu"
      - "&e/pvp toggleProfile &7Locks/Unlocks your profile"
      - "&e/pvp profile [player] &7Checks profile of yours or others"

chat-format:
  enabled: true
  format: "&7%player% &7%message%"

kill: # When attacker is set, public broadcasts aren't concluded.
  coins: 20
  messages:
    chat:
      victim:
        enabled: true
        message: "&cYou have been killed by &e%attacker%"
      attacker:
        enabled: true
        message: "&aYou have killed &e%victim% &6&l+%coins%G"
    action-bar:
      victim:
        enabled: true
        message: "&c&lYOU HAVE DIED!"
      attacker:
        enabled: true
        message: "&6&l+%coins%G"

deathMessages: # When attacker is not set, as well as public broadcasts.
  randomDeath:
    self:
      chat:
        enabled: true
        messages: # Random Messages
          - "&cYou have died!"
          - "&cWoah! Take care next time buddy!"
          - "&cHmm, that's weird..."
          - "&cHow?!"
      title-screen:
        enabled: true
        title: "&cYOU DIED"
        subtitle: ""
      action-bar:
        enabled: true
        messages: # Random Messages
          - "&cWHAT?!"
          - "&cAlright, better luck next time!"
          - "&cYou really should take care."
          - "&cHow about buying items? I think that will help."
    broadcast:
      enabled: true
      messages: # Random Messages
        - "&c%victim% has been killed by boredom."
        - "&c%victim% wasn't having a good day and died!"
        - "&cAfter a long journey, &e%victim% &chas died!"
  fireDeath:
    self:
      chat:
        enabled: true
        messages: # Random Messages
          - "&cThat was &6hot&c, wasn't it?"
          - "&cYou really should take care..."
      title-screen:
        enabled: true
        title: "&cYOU DIED"
        subtitle: ""
      action-bar:
        enabled: true
        messages: # Random Messages
          - "&cOuch!"
          - "&cHOT HOT HOT!"
    broadcast:
      enabled: true
      messages: # Random Messages
        - "&c%victim% caught on fire and died!"
        - "&c%victim% couldn't escape fire and died!"

profile:
  npc:
    name: "&b&lProfile"
    skinName: "Notch"
  guiName: "&6%query%'s &bProfile"

shop:
  npc:
    name: "&e&lShop"
    skinName: "HoneySalted"
  guiName: "&ePvP Shop"
  noEnoughCoins: "&cYou don't have enough coins to buy &e%query%"
  fullInventory: "&cYou don't have any free space to buy &e%query%"
  alreadyHave: "&cYou already have this item!"
  items:
    diamond_sword:
      canBuyMultipleOf: false
      amount: 1
      price: 300
      queryName: "&b&lDiamond Sword"
      gui:
        name: "&b&lDiamond Sword"
        lore:
          - "&7Left click: buy"
          - "&7Price: &e300"
      item:
        name: "&b&lDiamond Sword"
        lore:
          enabled: false
          lore:
            - "&1Deals +7 damage"
      purchaseMessage: "&aEnjoy your purchase!"
    diamond_leggings:
      canBuyMultipleOf: false
      amount: 1
      price: 700
      queryName: "&b&lDiamond Leggings"
      gui:
        name: "&b&lDiamond Leggings"
        lore:
          - "&7Left click: buy"
          - "&7Price: &e700"
      item:
        name: "&7"
        lore:
          enabled: false
          lore:
            - "&1Leggings armor"
      purchaseMessage: "&aEnjoy your purchase!"

scoreboard:
  title: "&6PvP"
  lines:
    - "&7Name &8» &e%player%"
    - ""
    - "&7Kills &8» &e%kills%"
    - ""
    - "&7Kill Streaks &8» &e%killStreaks%"
    - ""
    - "&7Deaths &8» &e%deaths%"
    - ""
    - "&7Coins &8» &e%coins%"
    - ""
    - "&ePlay.VampiresMC.com"